repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  # isort - Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Flake8 - Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-import-order]

  # MyPy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check for debugger imports and py37+ `breakpoint()` calls
      - id: debug-statements
      # Check whether the files parse as valid python
      - id: check-ast
      # Check for byte-order marker
      - id: check-byte-order-marker
      # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-builtin-literals
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check for debugger imports and py37+ `breakpoint()` calls
      - id: debug-statements
      # Don't commit to main branch
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']
      # Trim trailing whitespace
      - id: trailing-whitespace
      # Fix end of files
      - id: end-of-file-fixer
      # Check yaml files
      - id: check-yaml
      # Check toml files
      - id: check-toml
      # Check json files
      - id: check-json 