repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  # isort - Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Flake8 - Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [
          "--max-line-length=88",
          "--ignore=E203,W503,E501,D100,D104,D105,D107,D200,D205,D400,D401,F401,B007,E402,I100,I101,I201",
          "--max-complexity=50"
        ]

  # MyPy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests>=2.28.0
          - types-setuptools>=57.4.0
          - types-PyYAML>=6.0.0
          - types-six>=1.16.0
          - types-python-dateutil>=2.8.0
          - types-pytz>=2021.3.0
          - types-urllib3>=1.26.0
        args: [--ignore-missing-imports]

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check for debugger imports and py37+ `breakpoint()` calls
      - id: debug-statements
      # Check whether the files parse as valid python
      - id: check-ast
      # Check for byte-order marker
      - id: check-byte-order-marker
      # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-builtin-literals
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check for debugger imports and py37+ `breakpoint()` calls
      - id: debug-statements
      # Don't commit to main branch
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']
      # Trim trailing whitespace
      - id: trailing-whitespace
      # Fix end of files
      - id: end-of-file-fixer
      # Check yaml files
      - id: check-yaml
      # Check toml files
      - id: check-toml
      # Check json files
      - id: check-json
