name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd azul_rl
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Code formatting check (Black)
      run: |
        cd azul_rl
        black --check --diff .

    - name: Import sorting check (isort)
      run: |
        cd azul_rl
        isort --check-only --diff .

    - name: Lint with flake8
      run: |
        cd azul_rl
        flake8 .

    - name: Type checking with mypy
      run: |
        cd azul_rl
        mypy . || true  # Allow mypy to fail for now

    - name: Run tests
      run: |
        cd azul_rl
        pytest --cov=. --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./azul_rl/coverage.xml
        fail_ci_if_error: false 